<?php

/**
 * @file
 * Contains varbase_layout_builder.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block_content\BlockContentInterface;
use Drupal\media\Entity\Media;
use Drupal\media\MediaInterface;

/**
 * Implements hook_block_type_form_alter().
 */
function varbase_media_block_block_type_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
  if ($block_type == 'varbase_media_block') {
    if (isset($form['field_media_view_mode'])
        && isset($form['field_media_view_mode']['widget'])) {

      $form['field_media_view_mode']['widget']['#options'] = _varbase_media_block_active_media_view_mode_options();
    }
  }
}

/**
 * Get active media view mode options.
 */
function _varbase_media_block_active_media_view_mode_options() {
  $media_view_mode_options = \Drupal::service('entity_display.repository')->getViewModes('media');

  $ignore_view_mode_list = [
    'media.token',
    'media.slick',
    'media.media_library',
    'media.background_media',
    'media.browser_teaser',
    'media.field_preview',
    'media.varbase_media_hero_slider',
    '_none',
  ];

  foreach ($media_view_mode_options as $media_view_mode_option) {
    if ($media_view_mode_option['status'] == TRUE
        && !in_array($media_view_mode_option['id'], $ignore_view_mode_list)) {

      $active_media_view_mode_options[$media_view_mode_option['id']] = $media_view_mode_option['label'];
    }
  }

  return $active_media_view_mode_options;
}

/**
 * Implements hook_theme().
 */
function varbase_media_block_theme($existing, $type, $theme, $path) {

  $templates = $path . '/templates';
  $theme_templates = [];

  $theme_templates['block__inline_block__varbase_media_block'] = [
    'template' => 'block--inline-block--varbase-media-block',
    'path' => $templates,
    'base hook' => 'block',
  ];

  $theme_templates['block__block_content__varbase_media_block'] = [
    'template' => 'block--block-content--varbase-media-block',
    'path' => $templates,
    'base hook' => 'block',
  ];

  return $theme_templates;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function varbase_media_block_theme_suggestions_block_alter(array &$suggestions, array $variables) {

  if (isset($variables['elements']['content']['#block_content'])
      && $variables['elements']['content']['#block_content']->bundle() == 'varbase_media_block'
      && $variables['elements']['content']['#block_content'] instanceof BlockContentInterface) {

    $block_type_suggestion = 'block__block_content__varbase_media_block';
    $suggestions_rev = array_reverse($suggestions);
    $index = array_search('block__block_content', $suggestions_rev);
    if (is_numeric($index)) {
      array_splice($suggestions_rev, $index, 0, $block_type_suggestion);
      $suggestions = array_reverse($suggestions_rev);
    }
    else {
      $suggestions[] = $block_type_suggestion;
    }
  }
}

/**
 * Implements hook_preprocess_block().
 */
function varbase_media_block_preprocess_block(&$variables) {

  if (isset($variables['content']['field_media'])
      && isset($variables['content']['field_media_view_mode'])) {

    $block_field_media = $variables['content']['#block_content']->get('field_media');
    $block_field_media_view_mode = $variables['content']['#block_content']->get('field_media_view_mode');

    $media_id = $block_field_media->first()->getValue()['target_id'];
    $media = Media::load($media_id);

    if ($media instanceof MediaInterface) {

      $media_view_mode = $block_field_media_view_mode->first()
        ->getValue()['target_id'];
      $media_view_mode = str_replace('media.', '', $media_view_mode);

      $view_builder = \Drupal::entityTypeManager()
        ->getViewBuilder($media->getEntityTypeId());
      $field_media_output_with_selected_view_mode = $view_builder->view($media, $media_view_mode);
      $variables['content']['field_media'] = $field_media_output_with_selected_view_mode;

      $variables['content']['field_media'] = $field_media_output_with_selected_view_mode;
      unset($variables['content']['field_media_view_mode']);

      $variables['media_link'] = $variables['content']['field_link'];
      unset($variables['content']['field_link']);
    }

  }
  elseif (isset($variables['content']['content']['field_media'])
      && isset($variables['content']['content']['field_media_view_mode'])) {

    $block_field_media = $variables['content']['content']['#block_content']->get('field_media');
    $block_field_media_view_mode = $variables['content']['content']['#block_content']->get('field_media_view_mode');

    $media_id = $block_field_media->first()->getValue()['target_id'];
    $media = Media::load($media_id);

    if ($media instanceof MediaInterface) {

      $media_view_mode = $block_field_media_view_mode->first()->getValue()['target_id'];
      $media_view_mode = str_replace('media.', '', $media_view_mode);

      $view_builder = \Drupal::entityTypeManager()->getViewBuilder($media->getEntityTypeId());
      $field_media_output_with_selected_view_mode = $view_builder->view($media, $media_view_mode);

      $variables['content']['content']['field_media'] = $field_media_output_with_selected_view_mode;
      unset($variables['content']['content']['field_media_view_mode']);

      $variables['media_link'] = $variables['content']['content']['field_link'];
      unset($variables['content']['content']['field_link']);
    }
  }

}
