id: site_admin
permissions:
  - 'create varbase_featured_card_block block content'
  - 'delete any varbase_featured_card_block block content'
  - 'update any varbase_featured_card_block block content'
