<?php

/**
 * @file
 * Contains varbase_layout_builder.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function varbase_layout_builder_form_node_form_alter(&$form, FormStateInterface $form_state) {

  if (isset($form['actions'])) {
    $actions_array_keys = array_keys($form['actions']);
    foreach ($actions_array_keys as $action) {
      if ($action != 'preview'
          && isset($form['actions'][$action]['#type'])
          && $form['actions'][$action]['#type'] === 'submit') {

        $form['actions'][$action]['#submit'][] = '_varbase_layout_builder_form_node_form_submit';
      }
    }
  }
}

/**
 * Process the Varbase Layout Builder form node form submit.
 *
 * @param array $form
 *   The form object.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form status.
 */
function _varbase_layout_builder_form_node_form_submit(array &$form, FormStateInterface $form_state) {

  $node = $form_state->getFormObject()->getEntity();
  $node_type_display = \Drupal::service('entity_display.repository')->getViewDisplay('node', $node->bundle(), 'default');

  // Only When submitted after a new creation of a node with which it's
  // content type has an enabled layout builder on it's default display.
  if (!($form_state->getFormObject()->getOperation() === 'edit')
      && !empty($node_type_display)
      && $node_type_display->isLayoutBuilderEnabled()) {

    // Check if layout selection is not none.
    $layout_selection_is_none = TRUE;
    $layout_selection_value = $form_state->getValue('layout_selection');
    if (is_array($layout_selection_value)
        && isset($layout_selection_value[0])
        && $layout_selection_value[0]['target_id']
        && !empty($layout_selection_value[0]['target_id'])) {
      $layout_selection_is_none = FALSE;
    }

    // Get a valid edit layout url.
    $edit_layout_url = \Drupal::pathValidator()->getUrlIfValid('node/' . $node->id() . '/layout');

    // Have the permission name to change the layout for this content type.
    $bundle_permission_name = 'configure all ' . $node->bundle() . ' node layout overrides';
    $user = \Drupal::currentUser();
    $user_has_permission_to_manage_the_layout = ($user->hasPermission('configure any layout') || $user->hasPermission($bundle_permission_name));

    if (!empty($edit_layout_url)
        && $layout_selection_is_none
        && $user_has_permission_to_manage_the_layout) {

      // Remove destination if we do have it before we create the node.
      $request = \Drupal::request();
      if ($request->query->has('destination')) {
        $request->query->remove('destination');
      }

      $form_state->setRedirectUrl($edit_layout_url);
    }
  }
}
