id: seo_admin
permissions:
  - 'create varbase_impressed_card_block block content'
  - 'delete any varbase_impressed_card_block block content'
  - 'update any varbase_impressed_card_block block content'
