<?php

/**
 * @file
 * Contains List of all varbase_layout_builder updates.
 */

\Drupal::moduleHandler()->loadInclude('varbase_layout_builder', 'inc', 'include/updates/v8');
\Drupal::moduleHandler()->loadInclude('varbase_layout_builder', 'inc', 'include/updates/v9');
\Drupal::moduleHandler()->loadInclude('varbase_layout_builder', 'inc', 'include/updates/v10-0');
\Drupal::moduleHandler()->loadInclude('varbase_layout_builder', 'inc', 'include/updates/v10-1');
